{
 "title": "Proxysql Cluster Overview",
 "tags": [
  "mysql",
  "proxysql"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster_node",
    "label": "cluster_node",
    "query": "label_values(proxysql_uptime_seconds_total, cluster_node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Transactions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "proxysql_active_transactions{cluster_node=~\"$cluster_node\"}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(proxysql_slow_queries_total{cluster_node=~\"$cluster_node\"}[1m]) "
    }
   ]
  },
  {
   "title": "Connect Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "proxysql_connpool_conns_status{cluster_node=\"proxysql_node_1\"}"
    }
   ]
  },
  {
   "title": "Connection Pool Backend Latency (µs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "proxysql_connpool_conns_latency_us{cluster_node=~\"$cluster_node\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Fronted Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_client_connections_non_idle{cluster_node=~\"$cluster_node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "proxysql_client_connections_connected{cluster_node=~\"$cluster_node\"} - proxysql_client_connections_non_idle{cluster_node=~\"$cluster_node\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Backend Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(proxysql_connpool_conns{cluster_node=~\"$cluster_node\",status=\"used\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(proxysql_connpool_conns{cluster_node=~\"$cluster_node\",status=\"free\"})",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(proxysql_connpool_conns_queries_total{cluster_node=~\"$cluster_node\"}[1m]) ",
     "legendFormat": "{{hostgroup}}-{{endpoint}} "
    }
   ]
  },
  {
   "title": "Total Send / Receive Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(proxysql_queries_frontends_bytes_total{cluster_node=~\"$cluster_node\",traffic_flow=\"sent\"}[1m]))",
     "legendFormat": "Frontend Send Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_frontends_bytes_total{cluster_node=~\"$cluster_node\",traffic_flow=\"received\"}[1m]))",
     "legendFormat": "Frontend Receive Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_backends_bytes_total{traffic_flow=\"sent\",cluster_node=~\"$cluster_node\"}[1m]))",
     "legendFormat": "Backend Send Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_backends_bytes_total{traffic_flow=\"received\",cluster_node=~\"$cluster_node\"}[1m]))",
     "legendFormat": "Backend Receive Rate"
    }
   ]
  },
  {
   "title": "Command Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(proxysql_stats_mysql_commands_counters_total{cluster_node=~\"$cluster_node\", type=\"total_cnt\"}[1m]) >= 1",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Connection Statistics (irate conn/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(proxysql_client_connections_total{cluster_node=~\"$cluster_node\"}[1m]) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Command Elapsed Counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(proxysql_stats_mysql_commands_counters_total{cluster_node=~\"$cluster_node\",type=~\"cnt_10s|cnt_1s|cnt_500ms\"}[1m]) >= 1",
     "legendFormat": "{{command}}-{{type}}"
    }
   ]
  },
  {
   "title": "Top Counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,delta(proxysql_stats_mysql_query_digest_total{metric=\"count_star\",cluster_node=\"$cluster_node\"}[1m]))",
     "legendFormat": "{{digest}}"
    }
   ]
  }
 ]
}